# Header

menu:
  博客: /
  随笔: /essay

# SubNav
subnav:
  github: "https://github.com/leebolt528"
  #weibo: "#"
  rss: /atom.xml
  #zhihu: "#"
  qq: "http://wpa.qq.com/msgrd?v=3&uin=1277619140&site=qq&menu=yes"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:leebolt528@163.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"


# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '谢谢你请我喝咖啡'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /img/public/alipay.png
# 微信二维码图片地址
weixin: /img/public/wechat.png

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: false
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: '8678388163569c994a34c4a86608e4bb'
google_analytics: ''
favicon: /img/public/favicon.ico
cnzz_tongji:
     enable: true
     siteid: '1273322392'

#你的头像url
avatar: /img/public/head.jpg

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

#是否开启访客数量统计功能
counter: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  Pexels-免费高品质图片网: https://www.pexels.com/
  iconfont-阿里巴巴矢量图标库: https://www.iconfont.cn/home/index?spm=a313x.7781069.1998910419.2
  loding-加载动画: https://loading.io/
  ThoughtWorks-洞见: http://insights.thoughtworkers.org/tech-radar/
  

aboutme: 李博<br>趁年轻，我想来一次蹦极<br><br>
        爱健身,<br>爱生活,<br>爱自己<br><br>
        我这人不太懂音乐，<br>所以时而不靠谱，时而不着调.